### PR TITLE
build fix

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@CaptnCodr fyi, you `Remove dependencies that causes warnings` commit broke the build (and reveals the bug that our build script does not fail when build fails)

**Comment by CaptnCodr** [comment]
Yes, but I didn't see that the checks fail. 

Where can I see it?

**Comment by sergey-tihon** [comment]
https://github.com/fsprojects/FsUnit/runs/890780093#step:6:187

**Comment by CaptnCodr** [comment]
Ah, I see.

**Comment by CaptnCodr** [comment]
Well done.

**Pull request merged**
