### PR TITLE
Adding Support for CoreCLR

### PR DESCRIPTION
**Pull request by lynxluna**
- Adding Support for CoreCLR
- Updating Version Info to 2.3.0

NHamcrest uses my own feed, because it hasn't been updated for a while.

### CODE REVIEW

**Comment by aaronpowell** [comment]
What's outstanding to get this PR merged? I'd like to use fsunit with a .NET Core project

**Comment by sergey-tihon** [comment]
You can use it now with Paket - http://fsprojects.github.io/FsUnit/Paket.html
but I will take a look on this soon.. to get it merged.

@aaronpowell  what i do not like now it that we have to use NuGet again, together with paket. (maybe i am wrong here)

@lynxluna could you update this PR to latest .NET Core & dependencies + `dotnet-migrate` `project.json` to `.*proj` format?

**Comment by aaronpowell** [comment]
@sergey-tihon do you mean the need to take a dependency on NuGet for dotnet core stuff/package.json? I did notice that there's some NuGet config files in the PR, not sure exactly why they'd be need (I don't think I have them in any of my C# dotnet core projects)

**Comment by sergey-tihon** [comment]
@aaronpowell each project.json contains list of nuget packages with versions as I know

**Comment by aaronpowell** [comment]
Yep that's true. I think even with the move back to *proj it's not really going to get away from using NuGet for package loading

**Comment by cable729** [comment]
Would also love to use this in my .net core projects. What's left to get this merged?

**Comment by dbettin** [comment]
Any updates? Thanks for all of your work!

**Comment by sergey-tihon** [comment]
@dbettin Have tried to use [2.4.0-alpha2](https://www.nuget.org/packages/FsUnit/2.4.0-alpha-2) ?

**Comment by dbettin** [comment]
@sergey-tihon I have not. I will give it a try and let you know how it works.

**Comment by sergey-tihon** [comment]
@lynxluna Thank you for all you work, it helped a lot during migration to `netstandard`.

I close this PR in favor of #100 that create `FsUnit.NUnit` version on top on `netstandard1.6` that should make it available on all planforms. Please try latest beta [3.0.0-beta1](https://www.nuget.org/packages/FsUnit/3.0.0-beta1) and share your feedback in comments for #100

**Pull request closed without merging**
