### PR TITLE
NetCore support for xUnit and MSTest

### PR DESCRIPTION
**Pull request by alex-bogomaz**
Hello, please review this PR.
It adds NetCore support for xUnit

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@alex-bogomaz thank you!

Could you please rebase this PR on master (this may help with Travis build)

**Comment by alex-bogomaz** [comment]
@sergey-tihon - I noticed that on the latest  ```master``` we have following 
error when running ```build.cmd NuGetNUnitCore```:
```
dotnet "restore"
  Paket version 5.84.0
  Performance:
   - Runtime: 1 second
  Paket failed with
  -> FileNotFoundException: Could not find file 'D:\My\Projects\FsUnit-master\tools\paket.references'.
D:\My\Projects\FsUnit-master\.paket\Paket.Restore.targets(24,5): error MSB3073: The command ""D:\My\Projects\FsUnit-mast
er\.paket\paket.exe" restore --project "D:\My\Projects\FsUnit-master\tools\NuGetMerge.fsproj" --target-framework netcore
app1.0" exited with code 1. [D:\My\Projects\FsUnit-master\tools\NuGetMerge.fsproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Unable to find a project to restore! [D:\My\Projects\Fs
Unit-master\tools\NuGetMerge.fsproj]
dotnet mergenupkg --source "./../bin/FsUnit.3.0.0.nupkg" --other "./../src/FsUnit.NUnit/bin/Release/FsUnit.3.0.0.nupkg"
--framework netstandard1.6
No executable found matching command "dotnet-mergenupkg"
```
basically running ```dotnet restore``` in ```\tools``` dir is failing with following error:
```
  Paket failed with
  -> FileNotFoundException: Could not find file 'D:\My\Projects\FsUnit-master\tools\paket.references'.
```
Removing this line
```
  <Import Project="..\.paket\Paket.Restore.targets" />
```
from ```tools\NuGetMerge.fsproj``` fixes this problem and Nuget package with Netstandard ```FsUnit.NUnit``` is created fine.

Do you know anything about this?

**Comment by alex-bogomaz** [comment]
PR summary:
- NetCore support for xUnit & MSTest
- minor cleanup of NUnit code (removed ```AssemblyInfo.fs``` + some references cleanup)
- removed NUnitLite and use standart ```dotnet test```  for NetCore NUnit tests project
- ```dotnet-mergenupkg``` is restored via Paket
- MSTest NetCore - added ```Assert.That'``` because ```That``` property already exists in MSTest framework for NetCore - see https://github.com/Microsoft/testfx-docs/blob/master/RFCs/002-Framework-Extensibility-Custom-Assertions.md

Please review.

Work for future PRs:
- restore NetCore dependencies via Paket - now dependencies for NetCore projects are specified directly in fsproj files

**Comment by sergey-tihon** [comment]
Amazing work @alex-bogomaz !!! Thank you!

**Pull request merged**
