### PR TITLE
Adding strong name to FSUnit

### PR DESCRIPTION
**Pull request by parthopdas**
FSUnit.snk keypair is generated by Visual Studio. Using it to make the FSUnit binaries strong name signed.

### CODE REVIEW

**Comment by dedale** [comment]
@sergey-tihon Do your think this will be merged and deployed to nuget soon?

**Comment by sergey-tihon** [comment]
Sorry, I cannot help here. @dmohl is the only owner of NuGet packages and maintainer of this repo.
https://github.com/fsprojects/FsProjectsAdmin/issues/6

**Comment by dedale** [comment]
Thanks @sergey-tihon. I temporarily disabled signing in my test assemblies.

**Comment by sergey-tihon** [comment]
Why you need signing actually?

**Comment by dedale** [comment]
We sign everything at work. I may not need this anymore for a side project.
But if one day I start using fsunit in our main codebase, I might need
signing for compatibility with our clients.

**Comment by sergey-tihon** [comment]
What are the cons of signing `FsUnit` assemblies?
// cc @forki

**Comment by forki** [comment]
There is probably only pain if you sign test assemblies.

**Comment by dadhi** [comment]
You may sign nuget assemblies afterwards with https://www.nuget.org/packages/Nivot.StrongNaming. With whatever key. If you really need to.

Hope it helps.

**Comment by dedale** [comment]
Thanks for the input. Then I think we can close this issue.

**Comment by sergey-tihon** [comment]
@dedale Could you please clarify why do you sign test assemblies in your production codebase?

**Comment by dedale** [comment]
It is just that we used to sign all our assemblies since the early days of
.NET. I remember that at some time it was required to execute assemblies
from the network (as we did in our software factory).
Since we switched to .NET 4 with the new security model, we may not need
this anymore. Moreover that we do not run assemblies from remote shares
anymore.
But we never considered this.
As a side effect most of our clients also sign their assemblies so I fear
that we cannot disable signing for our production code.
But not signing unit test assemblies works (this is what I did).

**Comment by forki** [comment]
Yes you can keep signing production code, but here we're talking about unittest projects and signing unittest project infrasstructure.

**Comment by sergey-tihon** [comment]
@parthopdas Thanks for you work.
But I think that we are not going to sign `FsUnit` assemblies for now.

**Pull request closed without merging**
