### PR TITLE
Update NUnit to 3.11

### PR DESCRIPTION
**Pull request by theimowski**
This updates NUnit to 3.11 in lock file so that next version of FsUnit allows newest NUnit.

I needed to use the [`NUnit.Framework.PlatformAttribute`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/PlatformAttribute.cs) which is **not** available in NUnit 3.10.1 for netstandard2.0 but appeared in NUnit 3.11 for netstandard2.0.

Because FsUnit uses a [floating locked dependency](https://github.com/fsprojects/FsUnit/blob/master/src/FsUnit.NUnit/paket.template#L32), the requirements are currently following:

```
    FsUnit (3.2)
      FSharp.Core (>= 4.2.3)
      NETStandard.Library (>= 2.0.3)
      NUnit (>= 3.10.1 < 3.11)
...
    NUnit (3.10.1)
      NETStandard.Library (>= 2.0)
```

If I downgrade to FsUnit 3.1, the requirement on NUnit are less restrictive, and I can use 3.11

```
    FsUnit (3.1)
      FSharp.Core (>= 4.2.3)
      NETStandard.Library (>= 2.0.1)
      NUnit (>= 3.9 < 4.0)
...
    NUnit (3.11)
      NETStandard.Library (>= 2.0)
```

Maybe it might make sense to change the floating version to a major version?

### CODE REVIEW

**Comment by theimowski** [comment]
Travis failures seem to be unrelated

**Comment by sergey-tihon** [comment]
Thank you @theimowski !

**Comment by sergey-tihon** [comment]
Published as [v3.3.0](https://www.nuget.org/packages/FsUnit/3.3.0)

**Comment by theimowski** [comment]
great thanks!

**Pull request merged**
