### PR TITLE
Support of NUnit3

### PR DESCRIPTION
**Pull request by sergey-tihon**
https://github.com/fsprojects/FsUnit/issues/82

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Here I need a help to migrate two custom constrains
1) https://github.com/sergey-tihon/FsUnit/blob/master/src/FsUnit.NUnit/FsUnit.fs#L10-L18
2) https://github.com/sergey-tihon/FsUnit/blob/master/src/FsUnit.NUnit/FsUnit.Extra.fs#L6-L14
// cc @et1975 @damageboy

**Comment by Evangelink** [comment]
@sergey-tihon There is a PR (https://github.com/sergey-tihon/FsUnit/pull/1) on your forked repository. 
Don't know if there is a way to link it here so we have a chat only in one thread so I am copy-pasting my comment here:

> Based on NUnit3 source code I propose the following migration of the custom constraints.
> - We should add tests to prove the WriteDescriptionTo method migration is doing what is intended.
> - The F#-friendly formatting has been partially merged. We need to decide if the EqualConstraintResult class is good enough or if we inherit it and make it F#-friendly.

**Comment by sergey-tihon** [comment]
@et1975 where did you found info about pluggable formatters in NUnit?

**Comment by Evangelink** [comment]
> But WriteActualValueTo did it previously 

If you look between [NUnit3](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/XmlSerializableConstraint.cs) and [NUnit2](https://github.com/nunit/nunitv2/blob/master/src/NUnitFramework/framework/Constraints/XmlSerializableConstraint.cs) for the XmlSerializableConstraint class you will see the actual value is no longer displayed/printed. It seems it is now handled by the [ConstraintResult](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/ConstraintResult.cs) class.

@et1975 has opened an [issue](https://github.com/nunit/nunit/issues/1196) about that on NUnit.

**Comment by sergey-tihon** [comment]
Coool! Thank you @et1975

**Pull request merged**
