### PR TITLE
FsUnit.NUnit - netstandard1.6

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@enricosada Could suggest a way to run preview3 or preview4 on travis or appveyor?

**Comment by enricosada** [comment]
About travis appveyor ser https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/using-ci-with-cli

**Comment by sergey-tihon** [comment]
Thanks, but is does not work with `rc4` as I understand...
I heard that is possible to update tooling version from fake script...

**Comment by enricosada** [comment]
See https://github.com/dotnet/docs/blob/master/appveyor.yml and travis. Should work with rc4, is a normal zip file :)

**Comment by sergey-tihon** [comment]
How path to zip should looks like?
https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-RC4-004771/dotnet-dev-win-x64.1.0.0-rc4-004771.zip
I cannot guess the correct link to sdk )

**Comment by sergey-tihon** [comment]
Direct link to SDK binary works - "https://go.microsoft.com/fwlink/?linkid=841683"
so not AppVeyor is able to compile rc4 project 🤗

The issues that I have is here https://ci.appveyor.com/project/sergey-tihon/fsunit/build/0.0.1.61#L525
NUnit runner cannot load `nunit.framework` because it is not in `/tests/FsUnit.NUnit.Test/bin/Release/netcoreapp1.0/` folder. (as I understand it)

**Comment by enricosada** [comment]
@sergey-tihon you have PR to this PR https://github.com/sergey-tihon/FsUnit/pull/2

**Comment by sergey-tihon** [comment]
Heh, net core cannot run app of Mac OS
screen shot 2017-02-17 at 4 52 16 pm

**Comment by enricosada** [comment]
@sergey-tihon let me check

**Comment by sergey-tihon** [comment]
@enricosada Thank you for your guidance, seems like everything works now.

**Pull request merged**
