### PR TITLE
Add Expecto link to docs

### PR DESCRIPTION
**Pull request by CaptnCodr**
As discussed in #197, here we add Expecto to the docs. 

We can also add an extra section "MISCELLANEOUS" after "DOCUMENTATION" where we put some code samples of Flip.Expect, a link to it and nothing more.
Of course, we should mention that this is not included in FsUnit and all usable with Expecto.

All in this PR.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Would you like to add samples for `Flip.Expect`?

**Comment by CaptnCodr** [comment]
Yes, I will in the coming days.

**Comment by CaptnCodr** [comment]
It now looks like this:
image
Do we need more on it?

**Comment by sergey-tihon** [comment]
no, I think that it looks good for now.
Thank you @CaptnCodr !

**Comment by CaptnCodr** [comment]
Then I will deploy it soon-ish. 🙂

**Pull request merged**
