### PR TITLE
Add and unify badges

### PR DESCRIPTION
**Pull request by CaptnCodr**
This adds and unifies the badges in the Readme.md with shields.io badges.

1. Replaces github workflow badge [Line 5]
2. Adds the nuget dowload count badge and refers it [Line 6]
3. Adds the nuget version badge and refers it [Line 7]

@sergey-tihon I hope you like this little update. 🙂

### CODE REVIEW

**Comment by sergey-tihon** [comment]
I do not mind if merge this, but I also like badges from build stats
[NuGet Badge](https://www.nuget.org/packages/FsUnit)

**Comment by CaptnCodr** [comment]
This badge is maybe better. I'll take over this badge instead of the two new badges.

I just unified it, because the colors match among themselves.

**Comment by CaptnCodr** [comment]
So, then we have two badges. That would look like this:
image

Do you want some more?

**Comment by sergey-tihon** [comment]
No, I like it

**Pull request merged**
