### PR TITLE
Add collection supersetOf assertion for NUnit, xUnit and MsTest.

### PR DESCRIPTION
**Pull request by CaptnCodr**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
You are right! I like it! 

May I ask you to add few things:
- [ ] [Add it to the list of supported operators](https://github.com/fsprojects/FsUnit/blob/master/docs/content/operators.md)
- [ ] [All one line sample to home page](https://github.com/fsprojects/FsUnit/blob/master/docs/content/index.fsx)
- [ ] Add test case when sets are equal on both `[1..10] |> should (be supersetOf [1..10])`
- [ ] Ensure that error message is readable when it fails (for example `[1..10] |> should (be supersetOf [1..11])`)

I will be happy to merge this PR! 
Thank you @CaptnCodr

**Comment by CaptnCodr** [comment]
Now I changed the test names and added the new test case.

And I proposed the file changes for the operators and the one liners.

**Comment by sergey-tihon** [comment]
Released as v3.6.0
Thank you @CaptnCodr !

**Comment by CaptnCodr** [comment]
I'm very proud of it! 

Thank you too @sergey-tihon!

**Pull request merged**
