### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by CaptnCodr**

### CODE REVIEW

**Comment by CaptnCodr** [comment]
I'm considering changing the exception type as before (`MatchException`), but on the other side xunit has changed as the way that requires more code in F#. 

I'm not really sure to make this because it works as it is right now. 

What do you think @sergey-tihon?

**Comment by sergey-tihon** [comment]
I think that FsUnit should be as close to the underlying framework (xUnit) as possible. If xUnit throws another exception, we should not wrap it in the custom exception type. It should be a way to understand and use FsUnit if it behaves as an underlying framework.

**Comment by CaptnCodr** [comment]
Good point. 
I think this PR needs more work though. 🤔

**Comment by CaptnCodr** [comment]
I think this is ready now.

**Pull request merged**
