### PR TITLE
Added Xunit CustomMatcher to test case of union

### PR DESCRIPTION
**Pull request by b0wter**
I've added code to allow the user the check the case of a union (see #16). Example:
```
type MyUnion
    = One
    | Two
    | Three

First |> should be (ofCase<@ First @>) // this will succeed
Second |> should be (ofCase<@ First @>) // this will fail
```
Currently, this only works in Xunit. If you like the idea I'll try to add support for other frameworks.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Hi, thank you for the PR!

Can you please add tests for other frameworks?
- MbUnit out of scope
- MSTest should be relatively easy (reusing the same code from `CustomMatchers`)
- NUnit (if we can do it without `NHamcrest` dependency)

**Comment by b0wter** [comment]
Is there a good place to store common code?
For Xunit I simply wrapped a `CustomMatcher` around the two necessary methods. I guess it can be trivially done for Nunit and MSTest.

**Comment by b0wter** [comment]
I've updated my PR to include an implementation of `ofCase` for MSTest and NUnit. I've also added tests for them and updated the docs.
Since I didn't see a common code repository I've added the logic for `ofCase` twice (Xunit -> CustomMatchers and NUnit -> CustomConstraints).

**Comment by sergey-tihon** [comment]
Thank you for PR @b0wter !
Merged and released as v3.5.0

**Pull request merged**
