### PR TITLE
'samples' hyperlink, unicode symbols, dependencies

### PR DESCRIPTION
**Pull request by CaptnCodr**
- Fix 'samples' hyperlink in gh page. (#179 see following reference) 
> I happened to notice that the samples link is broken here. There should be a section or sample somewhere that explains this limitation and how to handle it.

- Move to unicode symbols in operators.md (fresher look than + (plus) or ' ' (empty) in column)

- paket restore (dependency updates)

@sergey-tihon What do you think?

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@CaptnCodr LGTM!

**Comment by CaptnCodr** [comment]
@sergey-tihon Do I only have to copy the generated .html files to `gh-pages` branch to update the FsUnit page (http://fsprojects.github.io/FsUnit/)?

**Comment by sergey-tihon** [comment]
execute `ReleaseDocs` target - https://github.com/fsprojects/FsUnit/blob/master/build.fsx#L210

```
./build.sh --target ReleaseDocs
```

**Comment by CaptnCodr** [comment]
I cannot generate new docs. I noticed when I push older docs to `gh-pages`
In the solution explorer there a `generate.fsx` but this has been removed somewhen.

**Comment by CaptnCodr** [comment]
@sergey-tihon `GenerateDocs` does only prints following and generates no docs:
image

This is weird.

**Comment by CaptnCodr** [comment]
So, I dropped the last commit on gh-pages to have the newer version. I accidently pushed docs from 23.11.2019.
Let's have a look ...

**Comment by sergey-tihon** [comment]
Docs were migrated to `fsdocs` sometime ago
https://fsprojects.github.io/FSharp.Formatting/upgrade.html

it strange that it broken now (project with docs is required)

please add one line to `FsUnit.NUnit.fsproj` (that should be the fix)
image

`dotnet fsdocs watch` should let you work on docs interactively.

There is a need to update template for latest version of fsdocs =( 
For example I see that placeholder names are changed , for example here https://github.com/fsprojects/FSharp.Formatting/blob/master/docs/_template.html#L68-L69

would be nice to diff and update out template where required

**Comment by CaptnCodr** [comment]
Yes, that works. After updating the template the tooltips are under the content:
image
Like on the current page with `https`: https://fsprojects.github.io/FsUnit/index.html

**Comment by CaptnCodr** [comment]
We could also drop the tooltips, everything else is looking fine.

**Pull request merged**
