### PR TITLE
Update copyright time period

### PR DESCRIPTION
**Pull request by CaptnCodr**
I overlooked the years here before the merge of #195.

@sergey-tihon We can also discuss about the license here. Did you think about that in the meantime? I'm neither an expert in licensing.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
I am also not an expert and I am more than OK to have MIT here

**Comment by CaptnCodr** [comment]
I copied it from here: https://ripcode.net/p/fsunit/license
Any additions?

**Comment by sergey-tihon** [comment]
No, looks good. (at least GitHub understand it)

**Comment by CaptnCodr** [comment]
Unfortunately, I'm not able to push the Nuget packages to nuget.org using `fake run build.fsx --target PublishNuGet`.
Err:  Paket failed with
->RequestFailedException: Request to 'https://www.nuget.org/api/v2/package' failed with: 400 BadRequest — Bad Request

**Comment by CaptnCodr** [comment]
I had no success with `licenseExpression` and reverted it to `licenseUrl`. I will look at it later.

Nuget package released as 4.2.0.

**Pull request merged**
