### PR TITLE
Added FsUnitTyped module + tests

### PR DESCRIPTION
**Pull request by sergey-tihon**
Added [typed version of FsUnit](https://github.com/forki/FsUnit/blob/master/FsUnit.fs) (created by @forki) as separate FsUnitTyped module.

Who want to see it packed in FsUnit distrib?
// cc: @forki 

- [x] Discuss publicly that this feature is requiried
- [x] Add documentation to `FsUnitTyped`
- [x] Check what open issues can fixed in `FsUnitTyped` by design and add appropriate unit tests

### CODE REVIEW

**Comment by tpetricek** [comment]
Yes yes yes yes yes yes please yesss!!!

[Unrelated rambling]
I would love it if you could also reference FsUnit just as a single file using the neat Paket file dependencies. This would avoid a bit of pain with configuring binding redirects and there really is no need for having to get a whole nuget package for this.
[/Unrelated rambling]

**Comment by sergey-tihon** [comment]
You already can reference `FsUnit.fs` as single file
http://fsprojects.github.io/FsUnit/Paket.html

the same true for `FsUnit.Typed.fs` after merging this PR

**Comment by tpetricek** [comment]
Woohoo!

**Comment by CraigStuntz** [comment]
First, I'm really happy to see this change!

Second, although using strong typed references does make things much better, it would be great to avoid `Assert.AreEqual` altogether, because the [implementation looks like this](https://github.com/nunit/nunit/blob/4e10f475d88fec980f080461a64e6fc4b1e54b2b/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs). I've opened [an issue on NUnit](https://github.com/nunit/nunit/issues/1249) about fixing that, but it may take a long time to implement.

**Comment by sergey-tihon** [comment]
@CraigStuntz So, you prefer something like this?
```fsharp
    [<DebuggerStepThrough>]
    let shouldEqual (expected : 'a) (actual : 'a) = 
        Assert.True((expected = actual), sprintf "Expected: %A\nActual: %A" expected actual)
```
instead of `Assert.AreEqual`?

**Comment by CraigStuntz** [comment]
@sergey-tihon I think I do, but I'm wondering if anyone uses FsUnit to test C# code? If so, not sure if `Assert.True(expect.Equals(actual), ...` would be better? Almost anything seems better than going into the `Assert.AreEqual` code, though.

**Comment by sergey-tihon** [comment]
@CraigStuntz  We can assume that nobody use `FsUnit` from C#.
At least I do not see any sense to do it.

We need to chose better way from F# perspective

**Pull request merged**
