### PR TITLE
.NET 5

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@CaptnCodr objections?

**Comment by CaptnCodr** [comment]
Implementing .NET 5 specific features e.g. string interpolation?

**Comment by CaptnCodr** [comment]
Is it even possible? I see that there is netstandard2.0 in the .fsproj files ...

**Comment by sergey-tihon** [comment]
> Is it even possible? I see that there is netstandard2.0 in the .fsproj files ...

I am not sure. We still should stay on `netstandard2.0` for NuGet package to be compatible with all runtimes.

> Edit: That's the same topic as we discussed / you taught me here: #158 (comment)

Maybe you are right, reverted it for now. Would be nice to upgrade it to 4.7 one day (this is lightweight netstandard2.0-only package)

**Comment by CaptnCodr** [comment]
But I think that Fsharp.Core 4.7.0 is long enough in the market to upgrade it to 4.7.0 for now.

**Pull request merged**
