### PR TITLE
New year's updates

### PR DESCRIPTION
**Pull request by CaptnCodr**
As mentioned in #225:
- Align `should` & `throw`. 
- Compile for .NET7. 
- Update copyright strings.
- Update dependencies.

### CODE REVIEW

**Comment by CaptnCodr** [comment]
Those two build failed with the same message as here: https://github.com/fsprojects/FAKE/issues/2719
I'll let it at version 5.23.1 and wait for FAKE 6 ...

**Review by sergey-tihon — APPROVED** [review]
@CaptnCodr thank you for this change. I am OK with this change, but what is the benefit of providing assemblies for .NET 7 ?

**Comment by CaptnCodr** [comment]
@sergey-tihon I'm investigating some details about that if the .dll in the package has some advantages when it's built with .NET7 (size, performance). I read that .NET7 is ~30% faster than .NET6.
Would be ready in the next days.

**Comment by CaptnCodr** [comment]
There is no difference in size of the libs. Performance is the same tho.
Nevertheless, I would ship it with the STS (.NET7) as we did in the past.

**Pull request merged**
