### PR TITLE
Upgraded fsharp.core to 4.0

### PR DESCRIPTION
**Pull request by JeremyBellows**
Also updated some other dependencies using `paket update`

I needed this to update the fsharp.core version to fix tests not compiling on appveyor. This commit fixes my issue.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
[Libraries should target lower version of FSharp.Core](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-target-lower-versions-of-fsharpcore), otherwise you limit the usage of the library.

What wrong with test AppVeyor? Could you post a link to the broken tests?

**Comment by JeremyBellows** [comment]
That makes sense. Thank you for enlightening me :+1: 

---------------

https://ci.appveyor.com/project/JeremyBellows/neuralfish/build/0.0.1.14

```
System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!0> FsUnit.Xunit.be()'.
```

**Comment by sergey-tihon** [comment]
Try to use packet to setup assembly redirect automatically
https://github.com/fsprojects/ProjectScaffold/blob/master/paket.dependencies#L3

**Comment by sergey-tihon** [comment]
or `paket install --redirects` but your test project should have `App.config` file.

**Comment by sergey-tihon** [comment]
And JFYI, since you are playing with NN - you way want tot try http://hypelib.github.io/Hype/

**Comment by JeremyBellows** [comment]
I'll try it out! 

The redirect worked! Thank you for the help and resources!

**Pull request closed without merging**
