### PR TITLE
Adding support for multi-target builds using Mono

### PR DESCRIPTION
**Pull request by atlemann**
- [x] Use netfx.props suggested by Don Syme.
- [x] Change FsUnit.MbUnit.fsproj to new SDK and fix build (not needed)
- [x] Figure out why I have to reference System.Runtime and System.Reflection

Fixes: #118

### CODE REVIEW

**Comment by atlemann** [comment]
Not sure what to do with MbUnit. I guess I could switch to new SDK for the project file and add the fix there to build on mono and just keep it on net45.

**Comment by atlemann** [comment]
Another thing, I had to add explicit references to System.Runtime and System.Reflection to get the build working, however I'm getting a lot of warnings about them not being found. Why do I have to add these?

**Comment by sergey-tihon** [comment]
We could ignore `MbUnit`, I do not even know how to run `MbUnit` tests under the full framework (I do not update this package anymore)

According to `FSharp.Core`, we definitely should use min possible version in `paket.dependencies`. I think that `4.1.18` is the good target, like [Expecto](https://www.nuget.org/packages/Expecto/) do `FSharp.Core (>= 4.1.18)`

**Comment by sergey-tihon** [comment]
@atlemann this is beautiful! It works!
I decreased version of `FSharp.Core` because of [Libraries should target lower versions of FSharp.Core](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-should-target-lower-versions-of-fsharpcore)

**Comment by atlemann** [comment]
Maybe we should just go back to what it was, since the page mentions that version: `Use FSharp.Core nuget 4.2.3 (assembly version 4.4.1.0) or 4.3.3 (assembly version 4.4.3.0)` so we don't pull in all those deprecated PCL targets?

Does the FullFramework target have to be as late as net46? Could we also target net45 as mentioned in the link?

I have been trying to find out why it needs System.Runtime and System.Reflection, but I cannot find any consistent answers and usually the fix seems to be to add an explicit reference. We might want add some assembly redirects, since I was getting a lot of warnings about "choosing version" etc. I can try to get rid of those warnings at least, before it's merged.

**Comment by atlemann** [comment]
I saw in Don Syme's comment that he also had to add references to some facade assemblies, so I guess that solution is fine. `System.Reflection` was required due to this error:

 /home/atle/src/FsUnit/src/FsUnit.Xunit/FsUnit.fs(9,6): error FS1108: The type 'TypeInfo' is required here and is unavailable. You must add a reference to assembly 'System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [/home/atle/src/FsUnit/src/FsUnit.Xunit/FsUnit.Xunit.fsproj]

**Comment by atlemann** [comment]
Looks like Travis CI lost its interwebs and Paket failed to download some deps. Other than that, I think I'm done.

**Comment by sergey-tihon** [comment]
@atlemann Thank you! Definitelymake sense to return to `FSharp.Core` `4.2.3` (will do)

We could try `net451` (because of `NHamcrest`) but IIRC there were compilation issues with versions lower `4.6`...

Should we update `paket.template` files to force reference `System.Reflection.dll` during NuGet package install?

**Comment by atlemann** [comment]
If there were issues with < net46 then we should just keep it like it is now. Do we have to force reference facade assemblies for runtime? I'm no expert when it comes to those things. I can try to google it, or we could try to ask someone.

**Comment by atlemann** [comment]
Found some old threads about this. Looks like there shouldn't be an explicit reference in the NuGet package, but maybe we'll have to try to create a nuget locally and try to use it from a net46 and netcoreapp2.0 projects.

https://github.com/aspnet/dnx/issues/2031
https://stackoverflow.com/questions/34136228/unable-to-resolve-assembly-reference-issue-without-frameworkassemblies

**Comment by sergey-tihon** [comment]
I think that we are good for now and ready to merge.
Since, nobody report issues, `3.1.0` works for users without explicit references.

**Pull request merged**
