### PR TITLE
Upgrade NHamcrest & drop NETStandard.Library

### PR DESCRIPTION
**Pull request by CaptnCodr**
- Upgrade NHamcrest in result of the .NET6 Upgrade on NHamcrest (https://github.com/nhamcrest/NHamcrest/pull/10)
- Drop netstandard2.0 (that was required for NHamcrest)

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Dropping `netstandard2.0` is a very big change, it means that we break everyone who still on .NET Framework...

What is new and cool in new NHamcrest? What is out motivation to upgrade?

**Comment by CaptnCodr** [comment]
Do we have statistics that shows how many dependents are still on .NET Framework? 

The root motivation is to get rid off .NET Framework/Standard in FsUnit with their dependencies to have only `net6.0` in the project files. 

We can also lose it a bit with shipping FsUnit in `net6.0` and `netstandard2.0` in the output, don't we?

**Comment by sergey-tihon** [comment]
> Do we have statistics that shows how many dependents are still on .NET Framework?
 
I believe that we do not have such statistic.

> New in NHamcrest is that is now in net6.0, but I see that may have to lose a bit with netstandard2.0, too.

Am I got it right that the only reason why NHamster is `net6` only is the number of dependencies? No other limitations? 

> We can also lose it a bit with shipping FsUnit in net6.0 and netstandard2.0 in the output, don't we?

This is absolutely good option.

**Comment by CaptnCodr** [comment]
> Am I got it right that the only reason why NHamster is `net6` only is the number of dependencies? No other limitations?

NHamcrest was a bit outdated with only .NET Framework and FsUnit needed to implement Netstandard.Library to work. 
NHamcrest has similar dependencies as FsUnit has, the output was just .NET Framework. 

So, FsUnit had to be on `netstandard2.0` in the project files and is now "free" which frameworks will be addressed. I'll lose the output on both, FsUnit and in the next version of NHamcrest.
It's clean to have everything as minimal as possible.

Thanks for pointing out.

**Comment by CaptnCodr** [comment]
So now, the output is now `net6.0` and `netstandard2.0` but no `NETStandard.Library` is explicitly referenced. 
We have basically a `net6.0` package but have a backward compatibility to `netstandard2.0`.

Users can simply get the `net6.0` library from our package without implementing `netstandard2.0` in their project files or consume the `netstandard2.0` library when their project is on e.g. `net47` or `netstandard2.0`.

In the end we're just referencing `NHamcrest` in `net6.0` and are getting rid of the `NETStandard.Library` reference.

**Comment by CaptnCodr** [comment]
@sergey-tihon is this ok for you how it looks right now? 🙂

**Review by sergey-tihon — APPROVED** [review]

**Comment by sergey-tihon** [comment]
LGTM 

Thank you @CaptnCodr  for this PR and all hard work to port `NHamcrest` to `net6`!

**Pull request merged**
