### PR TITLE
bump nunit version

### PR DESCRIPTION
**Pull request by JonCanning**

### CODE REVIEW

**Comment by yukitos** [comment]
ping.
When will this PR be merged? or rejected?

**Comment by sergey-tihon** [comment]
I think that we should merge it.
@yukitos Do you know any cons?

**Comment by yukitos** [comment]
No. Looks good to me :+1:

**Comment by trullock** [comment]
+1

**Comment by sergey-tihon** [comment]
@JonCanning Thank you!

**Comment by sergey-tihon** [comment]
Please try [FsUnit 1.3.1-beta](https://www.nuget.org/packages/FsUnit/1.3.1-beta) and let me know if it is OK

**Pull request merged**
