### PR TITLE
.NET Core 2.0 multi-target projects

### PR DESCRIPTION
**Pull request by sergey-tihon**
But we need to release from Windows machine =(

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Hi @ChrSteinert, may I ask you for help here? At least for review and advice ;)
I remember that I stuck with compilation for net45 on macOS/linux. does it already work?

**Comment by ChrSteinert** [comment]
Oh, I would be super happy to be of service. Let me have a look!

**Comment by ChrSteinert** [comment]
Got the first initially failing local builds to succeed now.
Will need some more time on this though. Will report back! ;)

**Comment by ChrSteinert** [comment]
🎉

**Comment by ChrSteinert** [comment]
@sergey-tihon let me know if I can help you with something!

**Comment by sergey-tihon** [comment]
Thank you @ChrSteinert TBH, no idea why it fails now =)

Should I explicitly reference https://www.nuget.org/packages/NETStandard.Library/ from `paket.dependencies` and reference in projects

**Comment by ChrSteinert** [comment]
I think previously the NETStandard.Library was a packages dependency. Maybe it is no more?

I'll have a look.

**Comment by sergey-tihon** [comment]
I cannot understand how it worked before... (with dotnet 2.0.3) if according to docs [Type.IsInstanceOfType](https://docs.microsoft.com/en-us/dotnet/api/system.type.isinstanceoftype?view=netframework-4.7.1#System_Type_IsInstanceOfType_System_Object_) is available only in `.NET Standard 2.0`

**Comment by sergey-tihon** [comment]
Thank you @ChrSteinert ! You saved me!

**Comment by ChrSteinert** [comment]
Anytime - been my pleasure!

**Pull request merged**
